### ISSUE TITLE
Unhandled error when starting the course

### ISSUE THREAD

**Issue by lundmikkel** [total-typescript/beginners-typescript-tutorial#83]
There's an unhandled error when [starting the course](https://www.totaltypescript.com/tutorials/beginners-typescript/beginner-s-typescript-section/implicit-any-type-error/exercise):

![image](https://github.com/total-typescript/beginners-typescript-tutorial/assets/1230950/a322a98e-3999-4d8d-b976-8cc2ad28baff)

```
Running tests...
failed to load config from /home/projects/kkvioyjzk.github/vite.config.ts

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: The package "esbuild-linux-64" could not be found, and is needed by esbuild.

If you are installing esbuild with npm, make sure that you don't specify the
"--no-optional" flag. The "optionalDependencies" package.json feature is used
by esbuild to install the correct binary executable for your current platform.
    at generateBinPath (file:///home/projects/kkvioyjzk.github/node_modules/esbuild/lib/main.js:1843:15)
    at esbuildCommandAndArgs (file:///home/projects/kkvioyjzk.github/node_modules/esbuild/lib/main.js:1901:31)
    at ensureServiceIsRunning (file:///home/projects/kkvioyjzk.github/node_modules/esbuild/lib/main.js:2065:25)
    at Module.build (file:///home/projects/kkvioyjzk.github/node_modules/esbuild/lib/main.js:1956:26)
    at bundleConfigFile (file://file:///home/projects/kkvioyjzk.github/node_modules/vite/dist/node/chunks/dep-5cb728cb.js:62943:35)
    at loadConfigFromFile (file://file:///home/projects/kkvioyjzk.github/node_modules/vite/dist/node/chunks/dep-5cb728cb.js:62919:31)
    at resolveConfig (file://file:///home/projects/kkvioyjzk.github/node_modules/vite/dist/node/chunks/dep-5cb728cb.js:62534:34)
    at Module.createServer (file://file:///home/projects/kkvioyjzk.github/node_modules/vite/dist/node/chunks/dep-5cb728cb.js:59137:26)
    at createVitest (file://file:///home/projects/kkvioyjzk.github/node_modules/vitest/dist/chunk-node-pkg.30d8b37e.js:13867:30)
    at async Module.startVitest (file://file:///home/projects/kkvioyjzk.github/node_modules/vitest/dist/chunk-node-pkg.30d8b37e.js:20259:15)

Failed. Try again!
```

**Comment by mattpocock** [comment]
Could you send this as feedback via the site itself? The team who maintain the site don't check these issues.
